.github/workflows/deploy.yml, config/settings.py, requirements.txt
delete setting branch ci/cd
set corsheaders
=> Feat: EC2 cd

accounts/models.py
사용자 모델 살짝 수정
```is_active``` 추가
```date_joined``` 추가
image는 ImageField로 변경
이제 createsuperuser로 만들어서 쓰면 됩니당
=> Fix: modify accounts/models.py

accounts/models.py, accounts/serializers.py, accounts/views.py
로그아웃 -> refresh_token DB에서 삭제
DB 업데이트 방식 수정
회원정보 미입력시 로그인 불가 -> 정보 입력으로 이동
user.nation에 Nation 객체 연결
```accounts/models.py``` - refresh_token 처리 및 업데이트 수정
```accounts/serializers.py``` - 회원정보 입력 여부 확인
```accounts/views.py``` - 회원정보 미입력시 정보 입력으로 이동 추가
=> Fix: signin

accounts/models.py, accounts/serializers.py, accounts/urls.py, accounts/views.py, config/settings.py, requirements.txt
1. 이메일로 인증코드 발송
2. 인증 코드 유효한지 확인
```accounts/models.py``` - 이메일 인증 코드 저장 모델, 인증 코드 랜덤 숫자 생성, 유효 시간 저장 추가
```accounts/serializers.py``` - AWS SES로 인증 코드 발송 + 재전송시에는 코드, 시간만 업데이트 / 인증 코드 여부 확인
```accounts/views.py``` - POST 메일 발송, GET 코드 인증
```config/settings.py``` - AWS IAM 사용자 & 이메일 발신 계정 추가
Issue #7 
[SES로 인증 코드 발송 및 코드 확인](https://pypy.dev/aws/aws-ses-for-email-verification/#1-%EC%9D%B8%EC%A6%9D-%EC%BD%94%EB%93%9C-%EC%83%9D%EC%84%B1)
[boto3 send_email](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ses/client/send_email.html)
+ 나중에 이메일 템플릿 html로 꾸며볼 예정
=> Feat: Feature/email

posts/models.py, posts/serializers.py, posts/urls.py, posts/views.py
SavedPosts 모델 추가 
게시물 스크랩, 스크랩 삭제 추가
`posts/models.py` - 스크랩 모델 정의 (user, post_en, post_kr, created_at)
`posts/serializers.py` - 모델 옮김
`posts/views.py` - SavePost 함수에서  POST, DELETE 정의 -> 나중에 함수 이름 바꿔야겠다
#18
=> Feat : posts 게시물 스크랩, 스크랩 삭제

posts/urls.py, posts/views.py
url parameter 수정
에러코드 변경
`posts/urls.py` - postid -> id로 변경 (저번 커밋 때 잘못 바꾼듯,,)
`posts/views.py` - 에러처리 및 에러코드 변경
=> Fix  : url param 수정 및 에러코드 변경

config/permissions.py, posts/models.py, posts/views.py
PostDetail GET 요청 시 로그인 인가 확인
Post image 필드 삭제 및 POST, PUT 요청 시 image 필드 삭제
`config/permissions.py` - GET 요청 시 로그인 확인, PUT, DELETE 요청 시 작성자인지 확인
`posts/models.py` - Post image filed 삭제
`posts/views.py` - permissions.py 적용, image filed 삭제
#22
=> Fix : PostDetail GET 시 로그인 인가 추가, Post image 모델 삭제

accounts/serializers.py, accounts/templates/email.html, requirements.txt
이메일 템플릿 추가
이메일 꾸미기..
```accounts/serializers.py``` - render로 html에 code 넣고 string으로 변환
```accounts/templates/email.html``` - html 템플릿
Issue #7 Design..
[Source Code](https://codepen.io/md-khokon/pen/bPLqzV)
유효시간 5분으로 아래 사진은 만료된 코드이니 걱정 안하셔도 됩니당
=> Design: set email template

config/settings.py, requirements.txt
S3 버켓 연결
profiles PUT에서 프로필 이미지 업로드 예정
```config/settings.py``` - DEFAULT_FILE_STORAGE에 버켓 연결
Issue #12
=> Chore: set s3 bucket

config/urls.py, posts/serializers.py, posts/urls.py, posts/views.py, profiles/urls.py, profiles/views.py
profile post, savedpost GET 요청 기능
자잘한 에러 수정 및 에러코드 수정
POST GET 요청 시profile_image 도 response
`posts/urls.py` - url '/' 추가
`posts/views.py` - 에러 메세지 수정 및 SavedPost Post 요청 시 "post_kr" 추가 (삭제했었는데, 테이블에 post_kr이 존재하긴 해서 post_en과 같은 값으로 보내줬어요)
`profiles/urls.py` - profile url 추가 
`profiles/views.py` - user_id를 키값으로 게시물을 불러와서 Response
`posts/serializers.py` - PostSerializer에 profile_image 추가
#25
=> Feat : profile GET post, savedpost

posts/urls.py, posts/views.py, profiles/urls.py, profiles/views.py
posts PUT 이 POST 와 같이 동작하던 문제 해결
url parameter CamelCase로 변경
`posts/urls.py`, `profiles/views.py` - postid, userid -> postId, userId
`posts/views.py` - **create_en_post**와 **create_kr_post**에 instance=None 인자를 추가 -> PUT 요청일 경우 instance에 값 넣어서 그 인스턴스를 수정하도록 변경,
**SavedPost** POST에서 post_kr이 post_en의 pk가 아닌 post_kr의 pk를 response하도록 변경
=> Fix : posts PUT 요청 수정, url parm Camelcase로 변경

accounts/models.py, accounts/templates/email.html, config/permissions.py, config/urls.py, profiles/serializers.py, profiles/urls.py, profiles/views.py
GET - 로그인 여부 확인 후 사용자 프로필 제공
PUT - 로그인, 본인 확인 후 username, profile_image, sns_link 수정 가능 (미입력시 자동으로 기존 데이터 연동 후 저장)
DELETE - 로그인, 본인 확인 후 is_active 처리
```accounts/models.py``` - PUT, DELETE 처리 및 image default 적용
```accounts/templates/email.html``` - s3 링크 노출 삭제
```config/permissions.py``` - 사용자 권한 커스텀
```profiles/serializers.py``` - 데이터 확인 및 반환
```config/urls.py``` - REST API
```profiles/views.py``` - 메소드 선언
#24
=> feat: 마이페이지 사용자 데이터

posts/views.py
삭제된 게시물은 PostList GET 요청 시 보내지 않음
`posts/views.py` - filter에 is_delete=False 추가
=> Fix : posts GET 요청 시 삭제되지 않은 게시물만 return

config/settings.py, places/models.py, places/serializers.py, places/urls.py, places/views.py
키워드로 DB에서 맛집 검색
```config/settings.py``` - 한국 시간 설정
```places/models.py``` - 맛집에 이미지 추가
```places/serializers.py``` - 국적 이름 반환 설정
```places/urls.py``` - search url 등록
```places/views.py``` - 페이지네이션 및 검색 결과 반환
#38
=> feat: 맛집 검색

places/serializers.py, places/views.py
places 내부 GET method 구현
```places/serializers.py``` - 국가 이름 추가
```places/views.py``` - places GET 추가 
#37 #42
=> Feat: places GET

profiles/serializers.py, profiles/urls.py, profiles/views.py
userId가 아니라 userName으로 profile 조회
username 중복 방지는 사전에 되어있음
```profiles/serializers.py``` - path variable 수정
```profiles/urls.py``` - url 수정
```profiles/views.py``` -  path variable 수정
=> Fix: profiles path variable 수정

posts/views.py, reviews/serializers.py
posts translate JSON 으로 변경
`posts/views.py` - 파싱 주석 처리하고,  JSON으로 받아서 처리
=> Fix : posts translation JSON으로 변경

posts/views.py, reviews/serializers.py
다시 translation 저장 방식 돌려놓음
`posts/views.py` - 이전 방식으로 돌림
=> Fix : translation 저장 방식 돌려놓음

places/models.py, places/serializers.py, places/views.py
places model nation 삭제 반영
```places/models.py``` - nation column 삭제
```places/serializers.py``` - 데이터 확인
```places/views.py``` - nation 삭제 반영
=> Fix: places model, serializer

places/serializers.py, profiles/urls.py, profiles/views.py
profiles의 places, reviews GET 구현
PlaceSerializer user 연결 수정
`places/serializers.py` - User과의 연결 파라미터 수정 user.id -> user_id.id
`profiles/urls.py` - url 추가
`profiles/views.py` - GET 구현
=> Feat : profiles GET places, reviews

places/models.py, places/serializers.py, places/views.py
모델에 content 추가
post, put, delete method 구현
```places/models.py``` - content 추가
```places/serializers.py```
```places/views.py``` - post, put, delete method 구현
#52
=> Fix: places post, put, delete

profiles/serializers.py
국적 정보를 안 준 바보 이슈 해결
```profiles/serializers.py``` - 국적 추가
=> Fix: profiles 국적 추가

places/serializers.py, places/views.py
사용자 이름 안 넘겨준 바보 이슈 #2
```places/serializers.py``` - 사용자 이름 추가
```places/views.py``` - post 요청에도 사용자 이름 추가
=> fix: 사용자 이름 추가

accounts/models.py, profiles/views.py
profile GetPlaces 등록한 맛집 없을 시 에러처리 추가
`accounts/models.py` - 포맷터로 인한 수정,, 신경 안쓰셔도 됩니다.
`profiles/views.py` - user가 등록한 맛집 없을 시 404 에러 처리했습니다.
=> Fix : profile GetPlaces 에러 처리

accounts/serializers.py, accounts/views.py
마이페이지 접근을 위한 username response에 추가
```accounts/views.py``` - response에 username 추가 !
=> fix: 로그인시 username 넘겨주기

places/models.py, places/serializers.py
자료형 수정 및 반환 데이터 추가
```places/models.py``` - 위도 경도 실수
```places/serializers.py``` - 사용자 프로필 이미지 추가
프론트 요청
=> Fix: 자료형 수정 및 반환 데이터 추가

places/views.py, posts/views.py, profiles/views.py
places PaceList GET 요청 시 tag 파라미터로 필터링
`places/views.py` - apply_filter 함수를 만들어서 필터링 적용함
`posts/views.py` - 조건문 합침
=> Feat : PlaceList Tag filter 추가

posts/views.py
post POST 에러 처리 추가
`posts/views.py` - 값이 안들어가도 에러가 안나서 에러처리 했습니다
=> Fix : post POST 에러 처리 추가

accounts/models.py, places/models.py, places/serializers.py, places/views.py, posts/serializers.py, profiles/serializers.py
=> fix: charfield->imagefield

places/serializers.py, places/views.py, profiles/serializers.py, profiles/views.py
=> fix: 이미지 반환 형식 수정

places/serializers.py, places/views.py, profiles/serializers.py, profiles/views.py
=> fix: places form data

accounts/models.py, profiles/serializers.py, profiles/views.py
=> fix: profiles PUT

places/views.py
SearchPlace Tag 쿼리 추가
`places/views.py` - 위에 정의되어있던 apply_filters 메서드를 사용해서 q 파라미터로 1차 필터링 후 tag 필터링 추가 (나머지는 포멧터입니다,,)
=> Fix : SearchPlace Tag 쿼리 추가

posts/views.py
translation에 \n 없이 내용 들어왔을 시 영어 제목은 No title, 한국어 제목은 제목 없음으로 처리후 저장
DELETE 부분 로직 수정
`posts/views.py` - parsing_translation 메서드를 수정해서 \n 없이 들어왔을 때 처리,
post_en과 post_kr은 있고, saved_post는 없을 시 에러처리가 돼서 post_en과 post_kr도 삭제할 수 없고 에러가 뜨는 경우가 있어서 로직 바꿈
=> Fix : posts POST, PUT translation \n 없을 시 처리
